
development:
  adapter: mysql2
  encoding: utf8
  database: user_authentication_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: user_authentication_test
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: user_authentication_production
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
